Repository SCCSEAOT/showcase-your-webpage, pull requests merged in 2022-10, with the labels that each got.

#2 Create arnab.html
  arnab/arnab.html
Labels: hacktoberfest-accepted, hacktoberfest

#3 Create srijan.html
  SRIJAN/srijan.html
Labels: hacktoberfest-accepted, hacktoberfest

#4 Update srijan.html
  SRIJAN/srijan.html
Labels: hacktoberfest-accepted, hacktoberfest

#5 Create srijan.css
  SRIJAN/srijan.css
Labels: hacktoberfest-accepted, hacktoberfest, newlable

#6 Create srijan.js
  SRIJAN/srijan.js
Labels: hacktoberfest-accepted, hacktoberfest

#11 Create PizzaLanding.html
  Prasun/PizzaLanding.html
Labels: hacktoberfest-accepted, hacktoberfest

#7 Create index.html
  Nishtha/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#8 I added Analog Watch in HTML
  Analog Watch/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#10 Musick webpage
  Shanit/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#16 Create clubSite.html
  MyClubPage/clubSite.html
Labels: hacktoberfest-accepted

#17 pics
  MyClubPage/pics/0c33d3ec-30b8-4ac5-9b69-bb311b994a9f.png
  MyClubPage/pics/48227582-a866-41ea-a0a2-56b3f9957ac5.png
  MyClubPage/pics/54617dcd-e054-4da2-a4f9-a7cdf79d71d5.png
  MyClubPage/pics/829b9576-69dd-43c7-aa30-5b1e31421723.png
  MyClubPage/pics/b5d8a417-92d3-4e5b-9e73-a44b423cb9b2.png
  MyClubPage/pics/bee.png
  MyClubPage/pics/block-courses.png
  MyClubPage/pics/c77e8af9-82c7-49ad-b05f-745e693f643a.png
  MyClubPage/pics/facebook2x-1.png
  MyClubPage/pics/facebook2x-2.png
  MyClubPage/pics/facebook2x.png
  MyClubPage/pics/instagram2x-1.png
  MyClubPage/pics/instagram2x-2.png
  MyClubPage/pics/instagram2x.png
  MyClubPage/pics/instructor.png
  MyClubPage/pics/linkedin2x-1.png
  MyClubPage/pics/linkedin2x-2.png
  MyClubPage/pics/linkedin2x.png
  MyClubPage/pics/model-black-courses.png
  MyClubPage/pics/owners_2-42.png
  MyClubPage/pics/pexels-karolina-grabowska-4491461.jpg
  MyClubPage/pics/pexels-katerina-holmes-5905709.jpg
  MyClubPage/pics/pexels-monstera-6238120.jpg
  MyClubPage/pics/play-video.png
  MyClubPage/pics/review-stars.png
  MyClubPage/pics/testimonio-46.png
  MyClubPage/pics/testimonio_2-46__1_.png
  MyClubPage/pics/twitter2x-1.png
  MyClubPage/pics/twitter2x-2.png
  MyClubPage/pics/twitter2x.png
  MyClubPage/pics/youtube2x.png
Labels: hacktoberfest-accepted

#18 Create digitalproduct.html
  DHRITI/digitalproduct.html
Labels: hacktoberfest-accepted, hacktoberfest

#19 Create QUIZ.html
  DHRITI/QUIZ/QUIZ.html
Labels: hacktoberfest-accepted, hacktoberfest

#12 Musick webpage_css
  Shanit/index.css
Labels: hacktoberfest-accepted, hacktoberfest

#13 refoldering this html
  Shanit/Musick/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#14 'how to contribute section added'
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#15 Create bijoya.html
  ds/bijoya.html
Labels: hacktoberfest-accepted, hacktoberfest

#20 Registration Form - KRISHNA
  RegistrationForm/index.html
  RegistrationForm/regform.css
Labels: hacktoberfest-accepted, hacktoberfest

#21 flipkartCloning.html
  Avik/flipkartCloning.html
Labels: hacktoberfest-accepted, hacktoberfest

#22 flipkartCloning.css
  Avik/flipkartCloning.css
Labels: hacktoberfest-accepted, hacktoberfest

#23 Created Log In page
  Sayan Das/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#25 Create index.html
  Rayoti/SimpleJobApplicationWebsite/first.html
Labels: hacktoberfest-accepted, hacktoberfest

#26 Create first_style.css
  Rayoti/SimpleJobApplicationWebsite/first_style.css
Labels: hacktoberfest-accepted, hacktoberfest

#27 html file added
  Jyotirmoy_SimpleCalculator/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#28 CSS file added
  Jyotirmoy_SimpleCalculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#30 js file added
  Jyotirmoy_SimpleCalculator/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#34 Update README.md
  README.md
Labels: hacktoberfest-accepted

#29 Adding My Portfolio Website
  Suvarnesh/404.html
  Suvarnesh/css/aos.css
  Suvarnesh/css/bootstrap.min.css
  Suvarnesh/css/main.css
  Suvarnesh/favicon.ico
  Suvarnesh/images/address_book.jpg
  Suvarnesh/images/cc-bg-1.jpg
  Suvarnesh/images/covid_19.jpg
  Suvarnesh/images/graphic-design-1.jpg
  Suvarnesh/images/graphic-design-2.jpg
  Suvarnesh/images/graphic-design-3.jpg
  Suvarnesh/images/graphic-design-4.jpg
  Suvarnesh/images/logo512.png
  Suvarnesh/images/logo64.png
  Suvarnesh/images/photography-1.jpg
  Suvarnesh/images/photography-2.jpg
  Suvarnesh/images/photography-3.jpg
  Suvarnesh/images/photography-4.jpg
  Suvarnesh/images/project-1.jpg
  Suvarnesh/images/project-2.jpg
  Suvarnesh/images/project-3.jpg
  Suvarnesh/images/project-4.jpg
  Suvarnesh/images/reference-image-1.jpg
  Suvarnesh/images/reference-image-2.jpg
  Suvarnesh/images/reference-image-3.jpg
  Suvarnesh/images/staticmap.png
  Suvarnesh/images/suvarneshkm.jpg
  Suvarnesh/images/todo-react.jpg
  Suvarnesh/images/todo_django.jpg
  Suvarnesh/index.html
  Suvarnesh/js/aos.js
  Suvarnesh/js/core/bootstrap.min.js
  Suvarnesh/js/core/jquery.3.2.1.min.js
  Suvarnesh/js/core/popper.min.js
  Suvarnesh/js/now-ui-kit.js
  Suvarnesh/js/plugins/bootstrap-datepicker.js
  Suvarnesh/js/plugins/bootstrap-switch.js
  Suvarnesh/js/plugins/jquery.sharrre.js
  Suvarnesh/js/plugins/nouislider.min.js
  Suvarnesh/manifest.json
  Suvarnesh/script.js
  Suvarnesh/scripts/main.js
  Suvarnesh/sworker.js
  profile.html
Labels: hacktoberfest-accepted

#35 Create index.html
  ARITRA/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#37 Create index.css
  ARITRA/index.css
Labels: hacktoberfest-accepted, hacktoberfest

#38 Create index.js
  ARITRA/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#41 create index.html
  supratim/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#40 Create index.html
  SHINJINI/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#39 Added my resume website written using Bootstrap, HTML, JS and CSS
  libinmv_resume/libinmv_resume.html
  libinmv_resume/src/resume.css
  libinmv_resume/src/resume.js
Labels: hacktoberfest-accepted, hacktoberfest

#36 signup_page
  .vscode/settings.json
  signup_page/signup.css
  signup_page/signup.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#47 Create index.html
  Rayoti/Hover Button/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#43 Updated the login form with the logo and UI
  Nishtha/index.html
  Nishtha/undraw_Male_avatar_re_hguk.png
Labels: hacktoberfest-accepted

#48 my_landing_page
  gitnandini/landing_page.html
Labels: hacktoberfest-accepted

#44 Analog clock
  Palak/analog clock
Labels: hacktoberfest-accepted

#42 added index.html
  abhijan/index.html
  abhijan/index.js
  abhijan/styles.css
Labels: hacktoberfest-accepted

#24 create index.html
  Supratim/index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#31 Added frontend of disney hotstar clone
  DisneyHotstarClone/images/add.png
  DisneyHotstarClone/images/disney.png
  DisneyHotstarClone/images/favicon.ico
  DisneyHotstarClone/images/geographic.png
  DisneyHotstarClone/images/logo.png
  DisneyHotstarClone/images/marvel.png
  DisneyHotstarClone/images/nxt.png
  DisneyHotstarClone/images/pixar.png
  DisneyHotstarClone/images/play.png
  DisneyHotstarClone/images/poster 1.png
  DisneyHotstarClone/images/poster 10.png
  DisneyHotstarClone/images/poster 11.png
  DisneyHotstarClone/images/poster 12.png
  DisneyHotstarClone/images/poster 2.png
  DisneyHotstarClone/images/poster 3.png
  DisneyHotstarClone/images/poster 4.png
  DisneyHotstarClone/images/poster 5.png
  DisneyHotstarClone/images/poster 6.png
  DisneyHotstarClone/images/poster 7.png
  DisneyHotstarClone/images/poster 8.png
  DisneyHotstarClone/images/poster 9.png
  DisneyHotstarClone/images/pre.png
  DisneyHotstarClone/images/slider1.png
  DisneyHotstarClone/images/slider2.png
  DisneyHotstarClone/images/slider3.png
  DisneyHotstarClone/images/slider4.png
  DisneyHotstarClone/images/slider5.png
  DisneyHotstarClone/images/star-wars.png
  DisneyHotstarClone/index.html
  DisneyHotstarClone/index.js
  DisneyHotstarClone/styles.css
  DisneyHotstarClone/videos/disney.mp4
  DisneyHotstarClone/videos/geographic.mp4
  DisneyHotstarClone/videos/marvel.mp4
  DisneyHotstarClone/videos/pixar.mp4
  DisneyHotstarClone/videos/star-war.mp4
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#32 I added a Tick Tac Game
  Tick Tac Game/index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#52 Create script.js
  Rayoti/Hover Button/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#54 I added a White Board
  White Board/Online-WhiteBoard/README.md
  White Board/Online-WhiteBoard/index.html
  White Board/Online-WhiteBoard/online_Whiteboard.png
  White Board/Online-WhiteBoard/script.js
  White Board/Online-WhiteBoard/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#51 Create index.html
  sulagna/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#56 Update styles.css
  ARITRA/index.css
  DisneyHotstarClone/styles.css
  Jyotirmoy_SimpleCalculator/style.css
  RegistrationForm/regform.css
  Sudoku-Solver/index.html
  Sudoku-Solver/styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#57 Update README.md
  README.md
Labels: hacktoberfest-accepted

#58 Resume webpage using html and inline css
  Resume Webpage
  abhijan/htm.html
Labels: hacktoberfest-accepted

#59 added portfolio
  code-soham/README.md
  code-soham/asset-manifest.json
  code-soham/assets/bg-st-stp.svg
  code-soham/assets/icons/aws.svg
  code-soham/assets/icons/c++.svg
  code-soham/assets/icons/canva.svg
  code-soham/assets/icons/css3.svg
  code-soham/assets/icons/gcp.svg
  code-soham/assets/icons/git.svg
  code-soham/assets/icons/github.svg
  code-soham/assets/icons/heroku.svg
  code-soham/assets/icons/html.svg
  code-soham/assets/icons/js.svg
  code-soham/assets/icons/mongodb.svg
  code-soham/assets/icons/mui.png
  code-soham/assets/icons/nodejs.svg
  code-soham/assets/icons/office.svg
  code-soham/assets/icons/postman.svg
  code-soham/assets/icons/pp.svg
  code-soham/assets/icons/python.svg
  code-soham/assets/icons/reactjs.svg
  code-soham/assets/icons/sparkar.png
  code-soham/assets/icons/sublime.svg
  code-soham/assets/icons/tailwind.svg
  code-soham/assets/icons/vscode.svg
  code-soham/code-soham.html
  code-soham/favicon.ico
  code-soham/logo192.png
  code-soham/logo512.png
  code-soham/manifest.json
  code-soham/robots.txt
  code-soham/static/css/main.3e35f1d3.css
  code-soham/static/css/main.3e35f1d3.css.map
  code-soham/static/js/787.0a7689f1.chunk.js
  code-soham/static/js/787.0a7689f1.chunk.js.map
  code-soham/static/js/main.a46eb33d.js
  code-soham/static/js/main.a46eb33d.js.LICENSE.txt
  code-soham/static/js/main.a46eb33d.js.map
  code-soham/static/media/revicons.57fd05d4ae650374c8de.ttf
  code-soham/static/media/revicons.a77de540a38981833f9e.eot
  code-soham/static/media/revicons.e8746a624ed098489406.woff
Labels: enhancement

#60 Library Database Management python
  Snigdha's Login Webpage/index.html
  Snigdha's Login Webpage/script.js
  Snigdha's Login Webpage/style.css
  Snigdha/__pycache__/librarym.cpython-38.pyc
  Snigdha/database/library2.sql
  Snigdha/librarym.py
Labels: hacktoberfest-accepted, hacktoberfest

#61 BISHAL.html
  BISHAL/BISHAL.html
Labels: hacktoberfest-accepted, hacktoberfest

#62 HOTELS.html
  BISHAL SEN/HOTELS.html
Labels: hacktoberfest-accepted, hacktoberfest
